[processor.generator.generate]
command = "rsslide"
args = ["generate", "--format=pdf"]
src_dirs = ["yaml", "out/import"]
src_extensions = [".yaml"]
output_dir = "out/generate"
output_extension = "pdf"
batch = true

[processor.generator.import]
command = "rsslide"
args = ["import"]
src_dirs = ["marp"]
src_extensions = [".md"]
output_dir = "out/import"
output_extension = "yaml"
batch = true

[processor.yamllint]
src_dirs = ["out/import"]
